In [8]:
import numpy as np

r1=int(input("enter the number of rows"))
c1=int(input("enter the number of columns"))
print("enter elements of first matrix:")
m1=list(map(int,input().split()))
m1=np.array(m1).reshape(r1,c1)
print("m1:\n",m1)

r2=int(input("enter the number of rows"))
c2=int(input("enter the number of columns"))
print("enter elements of second matrix:")
m2=list(map(int,input().split()))
m2=np.array(m1).reshape(r1,c1)
print("m2:\n",m2)

print("dot product:\n",np.dot(m1,m2))
print("transpose:\n",m1.transpose())
print("trace:\n",m1.trace())
print("rank:\n",np.linalg.matrix_rank(m1))
print("determinant:\n",np.linalg.det(m1))
print("inverse:\n",np.linalg.inv(m1))

x,y = np.linalg.eig(m1)
print("\nE-value : ")
print(x)
print("\nE-vector : ")
print(y)

enter the number of rows 2
enter the number of columns 2


enter elements of first matrix:


 1 2 3 4


m1:
 [[1 2]
 [3 4]]


enter the number of rows 2
enter the number of columns 2


enter elements of second matrix:


 1 2 3 4


m2:
 [[1 2]
 [3 4]]
dot product:
 [[ 7 10]
 [15 22]]
transpose:
 [[1 3]
 [2 4]]
trace:
 5
rank:
 2
determinant:
 -2.0000000000000004
inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]

E-value : 
[-0.37228132  5.37228132]

E-vector : 
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
